version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router1.rule=Host(`babol.localhost`)"
      - "traefik.http.routers.router1.entrypoints=web"

  whoami2:
    image: "containous/whoami"
    container_name: "simple-service2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router2.rule=Host(`whoami2.localhost`)"
      - "traefik.http.routers.router2.entrypoints=web"


  whoami3:
    image: "containous/whoami"
    container_name: "simple-service3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router3.rule=Host(`whoami3.localhost`)"
      - "traefik.http.routers.router3.entrypoints=web"

